language: bash
services: docker

env:
  - VERSION=latest

before_script:
  - env | sort
  - image="artb1sh/postgres-replication:$VERSION"
  - su-exec postgres psql -c 'create database travis_ci_test;'
script:
  - docker build -t "$image" .

after_script:
  - docker images
