version: '2.1'

services:
  pg-master:
    build: '.'
    image: 'artb1sh/postgres-replication'
    restart: 'no'
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      PGDATA: '/var/lib/postgresql/data/pgdata'
    volumes:
     - '/var/lib/postgresql/data'
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
    expose:
     - '5432'

  pg-slave:
    build: '.'
    image: 'artb1sh/postgres-replication'
    restart: 'no'
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      PGDATA: '/var/lib/postgresql/data/pgdata'
      REPLICATE_FROM: 'pg-master'
    volumes:
     - '/var/lib/postgresql/data'
    depends_on:
      pg-master:
        condition: service_healthy
    expose:
     - '5432'
    links:
     - 'pg-master'

